version: '3.8'

services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    container_name: app_gerencia
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - "8888:80"
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: db_gerencia
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_gerencia
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
