name: Run Codeception Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_gerencia
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      - name: Subir containers
        run: docker-compose -f docker-compose.yml up -d php

      - name: Rodar migrations
        run: docker exec app_gerencia php yii migrate --interactive=0

      - name: Rodar testes Codeception
        run: docker exec app_gerencia vendor/bin/codecept run
